### ISSUE TITLE
DoS download attack

### ISSUE THREAD

**Issue by sangorrin** [uptane/deployment-considerations#1]
An attacker in possession of one or more ECU private keys may launch a (D)DoS attack (HTTP flood [1]) on the image repository by continuously downloading update images at high speed. Such an attack, if successful, may result in the unavailability of updates to other ECUs.

OEMs should be able to detect and block such attacks, for example by revoking the offending ECU certificates, and possibly taking further measures offline such as recalling infected vehicles. Detecting HTTP flood attacks might be tricky and require domain expertise. For example, the attacker could emulate network timeouts just before a perfectly valid update image is completely downloaded. 

[1] https://www.imperva.com/learn/application-security/http-flood/

**Comment by tkfu** [comment]
Thank you for the suggestion, @sangorrin. However, ECU private keys/certs are not relevant to this discussion; the Uptane standard makes no prescription about authentication methods on the repository.

Because no Uptane-related key or protocol is implicated here, the problem you are describing is simply the general problem of dealing with DoS attacks. We consider that to be a fairly obvious part of best-practice server administration at scale. It wouldn't be appropriate to provide guidance on general server administration in Uptane's deployment considerations.

**Comment by jhdalek55** [comment]
Thanks, Jon. You handled that better than I could.

Lois

**Comment by sangorrin** [comment]
Hi @tkfu thanks for your answer.
