### ISSUE TITLE
Deployment Considerations References to "Recall"

### ISSUE THREAD

**Issue by allen-cain** [uptane/deployment-considerations#47]
The Deployment Considerations "Key Management" page has several references to `recall`.

<ins>**Proposal:**</ins> Remove all references to `recall` in favor of terminology allowing an OEM to safely and securely handle the revocation, rotation, and updating of cryptographic material.

**Comment by mnm678** [comment]
It should be possible to replace the word `recall` with a more general term without losing the security properties intended. 

Specifically, any situation that requires revoking a root key (which should be very rare if a threshold of offline keys are used) must be handled through a channel that is more secure than the root key itself. If this secure channel is another over-the-air mechanism, the security of Uptane now relies on the security of this external channel (because this channel has permission to replace arbitrary root keys). For this reason, I would suggest we recommend that an in-person mechanism is used for replacing root key information.

Does anyone have suggestions for how to word this requirement in a more general way?

**Comment by plapczyn** [comment]
Could we use "update" instead of "recall" in key_management.md?

**Comment by iramcdonald** [comment]
Based on today's Uptane call, I suggest that for v1.1.0 we should:
(1) Replace "recall" with "update" in our Key Management section
(2) Add an early reference to IETF RFC 4107 / BCP 107 (that latter is important)
Guidelines for for Cryptographic Key Management, which is advice for protocol
designers on the use of automated KMS versus manual KMS.
(3) Defer the larger rewrite/extension of Key Management section of Deployment
Considerations for v2.0.0 (because Jon's right in saying that misuse of keys in the
supply chain is a attack surface in all OTA systems).
