### ISSUE TITLE
Should a metadata file still be valid if it meets the threshold of valid signatures, but also includes one or more invalid signatures?

### ISSUE THREAD

**Issue by tkfu** [uptane/deployment-considerations#48]
Title mostly says it all, but I'll flesh out a couple of examples:

Root metadata says valid top-level targets keyids are `a`, `b`, `c`, and `d`, with a threshold of 2. Should the following two metadata files be considered valid?

* Signed by `a`, `b`, and `x`, where `x` is not present at all in root metadata
* Signed by `a`, `b`, and `c`, but `b`'s signature doesn't actually match the signed content

I believe that, as the standard is currently written, an implementor could interpret it either way. My initial opinion is that it's fine to leave this choice up to implementors, but I'd like to get more input if there's a strong case to be made that we should specify one behaviour or the other.

**Comment by jhdalek55** [comment]
@tkfu what needs to be done if this clarification is to be part of the 1.1.0. If its a wording clarification, what should it say and where should it go?

**Comment by jhdalek55** [comment]
On our 9/15 call we decided to acknowledge this issue, but not within the formal text of the Deployment pages. Instead we decided to include an FAQ page in the document for issues like this that may not be common use cases, but still should be acknowledged.

**Comment by jhdalek55** [comment]
I drafted the following text in response to this issue. Before I move this onto the FAQs page, I wanted @JustinCappos and @tkfu  to see if it makes sense. I literally used your words. I just tried to combine them into a statement rather than a question. Let me know if this works. 
------------------------
Must all signatures be valid for a threshold of signatures to be valid?  

The threshold rule of Uptane stipulates that a set number of keys are required to sign a metadata file. This is designed to complicate matters for would-be hackers by forcing them to compromise multiple  keys in order to install malware. However, what happens if this threshold is met, but one or more of the keys is not valid?

As currently configured, the Uptane Standard allows each implementer to decide whether these keys would be accepted. Take the following example:
 
Root metadata says valid top-level targets keyids are a, b, c, and d, with a threshold of 2. Should the following two metadata files be considered valid?

- Signed by a, b, and x, where x is not present at all in root metadata
- Signed by a, b, and c, but b's signature doesn't actually match the signed content

The first case can happen when you include x in a newer version of root metadata (for example the next iteration), so this has to be handled correctly or it will complicate  the process of adding and rotating keys. The second case could happen when you are changing or adding signing algorithms. This case can occur if B is using a signing scheme and the client doesn't notice, but will know how to parse it after the update.

Both the Uptane Standard and the Reference Implementation consider both of these cases valid  and the implementation also includes unit tests to verify this  behavior. 

We would welcome input from the community as to whether a case can be made for specifying one option over another.

**Comment by patrickvacek** [comment]
@jhdalek55 looks generally fine to me, with a few minor caveats. Might be easier to discuss it as a PR, though. :)

Comments so far:
* "The threshold rule of Uptane" -> we should provide the section number and link to it.
* "This is designed to complicate matters for would-be hackers by forcing them to compromise multiple keys in order to install malware." -> I feel like this could be phrased better. I don't like saying we are "forcing" hackers to do something; I'd prefer to say we are "preventing" something.
* We are inconsistent about how we spell "implementer"/"implementor".
* In the signature example, I'd prefer if we capitalized the role letters.
* "This case can occur if B is using a signing scheme" -> "using a *new* signing scheme"

**Comment by jhdalek55** [comment]
Thanks for the comments.  Here are my replies to a few of them. We can certainly talk more about this tomorrow at the meeting. 

I agree we need the section number linking to the "threshold rule." I had planned to include it, but frankly I couldn't find where it was stated as a rule. I could only find references to the rule, but nothing stating that it was a rule. I think we just adopted this as one of the principles we took from TUF. I'll take another look as I'm proofreading the text. If you know where it should go, please let me know.

**Comment by jhdalek55** [comment]
We decided at some point in favor of "implementer" as this has become the commonly accepted form of the word. I thought we had already adjusted for that but, if not, I will check it while proofreading.

The role letters should be capitalized (not the word 'role" bu Targets, etc.) and again I will fix it here.

Thanks.

**Comment by patrickvacek** [comment]
> I agree we need the section number linking to the "threshold rule." I had planned to include it, but frankly I couldn't find where it was stated as a rule. I could only find references to the rule, but nothing stating that it was a rule. I think we just adopted this as one of the principles we took from TUF. I'll take another look as I'm proofreading the text. If you know where it should go, please let me know.

See for example https://uptane.github.io/uptane-standard/uptane-standard.html#check_root, section 5.4.4.3 step 2.3: "Version N+1 of the Root metadata file MUST have been signed by the following: (1) a threshold of keys specified in the latest Root metadata file (version N), and (2) a threshold of keys specified in the new Root metadata file being validated (version N+1). If version N+1 is not signed as required, discard it, abort the update cycle, and report the signature failure. On the next update cycle, begin at version N of the Root metadata file. (Checks for an arbitrary software attack.)" The sections for the Timestamp, Snapshot, and Targets have similar phrasing.

> We decided at some point in favor of "implementer" as this has become the commonly accepted form of the word.

Sorry, I think I'd forgotten that we'd actually made a decision. I think there are still with the other spelling but that's not related to this!

> The role letters should be capitalized (not the word 'role" bu Targets, etc.) and again I will fix it here.

I was actually specifically talking about the letters a, b, c, d, and x in the example. I would prefer if it read, for example, "Signed by A, B, and X, where X is not present at all in Root metadata".

**Comment by jhdalek55** [comment]
Last point makes sense. I will fix it.

**Comment by jhdalek55** [comment]
I can open the corrected copy as a PR.

**Comment by JustinCappos** [comment]
This looks good to me.  I think this is a valid case we should clarify.

**Comment by patrickvacek** [comment]
Closed by https://github.com/uptane/deployment-considerations/pull/59.

**Comment by jhdalek55** [comment]
Closed via Pull Request #59
