### ISSUE TITLE
"Copy all unencrypted images from the Image repository."

### ISSUE THREAD

**Issue by pattivacek** [uptane/deployment-considerations#75]
In the "What the OEM should do" section of the [repositories page](https://uptane.github.io/deployment-considerations/repositories.html), we claim that to set up the Director repo, one should "[c]opy all unencrypted images from the Image repository." Isn't that only necessary if per-device encryption is being used? Or am I missing something?

It's also confusing that we describe the Director repo first, yet say that we should copy images from the Image repo. That's a minor crime, though.

**Comment by jhdalek55** [comment]
Answering the second comment first, I agree its a bit odd to reference something that hasn't been introduced yet. My impulse, though, is to leave that be for now...unless it really disturbs you or another reviewer.

As for the first point, I know we just wrestled with the issue of encrypted images on the Image repository and resolved it by stating that encrypted or unencrypted doesn't matter on the repo (except, as you pointed out, if we are talking about per-Device encryption. I can't flip over this second to check the context, but could this resolved by removing the word "unencrypted," since the Director is going to treat them the same way?

**Comment by pattivacek** [comment]
> could this resolved by removing the word "unencrypted," since the Director is going to treat them the same way?

You make a good point that we probably should remove the word "unencrypted", but even that doesn't fully address my concern. My main issue is that I don't understand why we would need to copy all of these images if the Director won't be storing them. If the Director is storing per-device encrypted images, then sure, go for it, but if not, I don't see a reason to do that copy operation.

**Comment by pattivacek** [comment]
So perhaps my proposal would be to change it to this:

"If the Director will be serving per-device encrypted images, copy all relevant images from the Image repository."

**Comment by jhdalek55** [comment]
@trishankkarthik  or @mnm678  would the above proposal work?
