### ISSUE TITLE
How do we secure data during transport?

### ISSUE THREAD

**Issue by jhdalek55** [uptane/deployment-considerations#8]
Version 1.0 of the Uptane Standard incorporates nothing about controlling security when data is transported between the server and the primary. What strategies can be recommended to address this security gap?

**Comment by jhdalek55** [comment]
Note that we have a brief write-up basically stating that our systems does not explicitly cover transport security,  and mentioning what systems for transport security can be used with Uptane. This is on the Customization page under the heading of "Uptane in conjunction with other protocols." Is that sufficient for now?

**Comment by JustinCappos** [comment]
Yes, but we should change this to be more clear that we do not rely on any
transport security mechanism.  It's implicit now.

**Comment by jhdalek55** [comment]
Ok. So if the existing text just needs to be made more explicit, then perhaps I can take a run at it and see if the point can be strengthened.

**Comment by jhdalek55** [comment]
The existing text can be found on the 'Customizations" page as follows:
https://github.com/uptane/deployment-considerations/blob/master/customizations.md#uptane-in-conjunction-with-other-protocols.

I will take a first pass at clarifying this text.

**Comment by JustinCappos** [comment]
Based upon the conversation today, I wanted to discuss a little more about what Uptane "loses" if there is a man-in-the-middle attacker.  

The security loss I see is that an attacker can do a freeze attack or just block updates.  The vehicle will quickly become aware of the issue, and this error can be surfaced in an appropriate manner.

One issue I heard raised is that one needs to have transport level security for authenticating the car to the director server / inventory server and vice versa.  I do not believe this to be the case.  The ECUs in the car have the public keys of the various roles on the director and image repositories.  Hence the ECUs know they are speaking with a party that produces signed metadata from those parties.  So, an attacker could do a freeze attack, much like just blocking or replaying old metadata which is the baseline impact of a network attacker.

Conversely, the director / inventory server needs to authenticate the ECU manifests.  The director stores keys (either a symmetric or a public key per ECU) so it can authenticate that the manifest comes from the reported ECU.  An attacker can block these manifests, but this also is the baseline impact from a network attacker.

Am I missing something?  Are there other concerns?   @iramcdonald

**Comment by iramcdonald** [comment]
Hi,

Speaking from my six years of cybersecurity work (mostly on OTA updates)
with three different automotive OEMs, their reasons for mandatory strong
transport security include:

(1) Defense-in-Depth - if only signatures are checked on protocol objects
(manifests, images, metadata) are checked, then only application layer
security is present - IETF, ISO, ITU-T, ETSI best practices and standards
in the area of automotive updates (firmware, configuration, and policies)
all mandate strong transport layer security (and often also strong datalink
layer security).

(2) Mutual authentication for Endpoints - prevents MiTM attacks (leading
to freeze or block attack modes), except where the entire PKI backend of
an OEM has been corrupted (in which case OTA updates will be turned
off until the catastrophe has been mitigated).

(3) Data-inTransit Integrity - complements Data-at-Rest Integrity in the
OEM Image Repositories and OEM Vehicle Inventory Databases and
again prevents MiTM attacks.

(4) Remote Attestation of Endpoint Posture - the topic of IETF RATS
WG - can be bundled with application data objects in a secure transport
connection - this allows active *proof* of the hardware and software
integrity of the Endpoint systems from Secure Boot on up to Runtime
Integrity Monitoring (the topic of IETF SACM WG).

That 4th topic is the principal current area of collaboration of Trusted
Computing Group (TCG), Global Platform (GP), and ETSI.  Without
strong Transport security, Remote Attestation cannot be bundled into
pure Application layer object security (according to IETF RATS WG).

Uptane can choose to ignore these topics.  Thanks to regional and
national existing and near-future cybersecurity regulations, OEMs
can't choose to ignore these topics.

Cheers,
- Ira


Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
Okay, I feel like we're agreeing on the technical aspects and our biggest
disagreement is how to present this.  Perhaps a way of phrasing this
differently is that Uptane provides strong security even when transport
security fails.  Do you feel this would be a good resolution, or do you
think there is a better way to convey this?

**Comment by iramcdonald** [comment]
Hi Justin,

I don't agree with your summary.

No single layer set of security guarantees is as strong as multiple
protocol layer security guarantees combined with Endpoint system
integrity proofs and active runtime monitoring.

Uptane focuses on application layer security guarantees.  That's
fine.  But it does NOT mitigate the loss of "defense-in-depth".
Uptane application layer security alone conflates possession of
key material with the health of the endpoints using those keys.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
Okay, so when we threat modeled Uptane, we also focused on explaining what
the ramifications were of not making a choice.  I'm thinking back to those
tables with the icons for different attacks that I'm so fond of showing
during meetings.

Uptane + transport layer security is stronger than Uptane.  Heck, Uptane +
anything that provides epsilon more security is stronger by definition.

My thrust here was to try to explain concretely in terms of attacker
capabilities what the difference is when you have a compromised or insecure
transport layer security system you use with Uptane.  I think what you're
saying is that if you have a secure transport mechanism that isn't
compromised, then it provides yet another layer of defense even if there is
also a director repo + primary + image repo + offline image repo key
compromise?

Is this correct or am I missing something?  Does the table change in
another way?  Do we need to add a row or field?  I feel like I'm being
really dense here, so apologies if I'm still missing your point.

**Comment by iramcdonald** [comment]
Hi Justin,

OK - I agree that Uptane + any security enhancement at another layer
or in the end system ECU itself provides stronger security than just
Uptane.  And that Uptane does address that variety of attacks in the
diagrams.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
Okay, let me take another cut at some proposed text.  I'd like to include
both perspectives in the new text, both saying our threat model isn't
significantly weakened if transport layer security fails and also
explaining that it is stronger with it plus there may be regulatory,
compliance, redundant auth, etc. reasons.

Does this approach seem like a good compromise?  If so, I'll write up
something and we can wordsmith from there...

**Comment by jhdalek55** [comment]
This seems to make the most sense.

**Comment by iramcdonald** [comment]
Hi Justin,

In *any* protocol, if a receiver detects that Transport layer security has
failed, it MUST discard everything received, abandon the transaction,
and securely log a fatal error.

So I think you still need to be a bit careful about your wording.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
I might be reading something wrong into what you're saying, so apologies if
this is off-base...

If a transport layer key is compromised (i.e., an edge server is broken
into), what should the response be apart from logging and erroring?  How
does the system get back to a secure state if the transport layer key it
trusts may be under the control of an attacker?

Also, is detecting such an error a common outcome of a successful attack?
I'm not sure how a recipient would usually detect such an attack has
occurred...  It seems much more likely that a cryptographic integrity check
on transmitted data fails due to a network error than a malicious attack.
The checks in lower level networking protocols usually filter these out,
but in rare circumstances (often involving hardware errors in networking
equipment), they have been known to slip through.

In my view attacks on the transport layer keys / servers are the most
frequently successful attack an OEM will face.  As I understand it, we'd
like for the system to be able to securely recover from such a state
without forcing every vehicle to go to a dealership, if possible.

**Comment by iramcdonald** [comment]
Hi Justin,

I have zero time in the next two weeks, so a quick response.

Applications using TLS for transport security SHOULD have redundant
credentials for
communicating with remote servers (such as the Director).  Otherwise, there
is no
possible recovery.  Likewise a Director SHOULD have redundant TLS
credentials for
communicating with Image Repository and Vehicle Inventory Database servers.

The whole of the ITS (Intelligent Transportation System) standards from
IEEE, ITU-T,
ETSI, and ISO are predicated on the fact that *all* end systems and servers
always
have redundant valid keys active at all times.  Otherwise
single-point-of-failure means
that the underlying vehicle safety messages will be lost.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
Perhaps we should shelve this discussion for now and revisit in either the
next meeting or a separate meeting specifically on this topic...

**Comment by jhdalek55** [comment]
It appears there is a lot more to discuss with this issue. Shall I add it to the agenda for our 10/1 meeting? 

If this perhaps is going to take a few iterations to address correctly, might it be possible to agree on some general broad wording in the meantime? The current reference to this issue on this site is on the "Customizations" page at https://github.com/uptane/deployment-considerations/blob/master/customizations.md#uptane-in-conjunction-with-other-protocols. Can this text remain as is until we resolve the bigger picture?

**Comment by jhdalek55** [comment]
I put this issue on our meeting agenda, though I believe it might warrant a separate call. I would still like some consensus on whether the existing text is sufficient for now.

**Comment by iramcdonald** [comment]
Hi Lois,

In Deployment Considerations, all of the OEM contributors have at one time
or another asked for a considerably deeper treatment of Transport Security.

Earlier in this long and winding thread, Justin said:

"Based upon the conversation today, I wanted to discuss a little more about
what Uptane "loses" if there is a man-in-the-middle attacker.

The security loss I see is that an attacker can do a freeze attack or just
block updates. The vehicle will quickly become aware of the issue, and this
error can be surfaced in an appropriate manner."

But the error will NOT be surfaced!   The complete loss of connectivity to
the OEM Director from the vehicle CANNOT be reported to the OEM Director
(or effectively detected by the OEM Director, because the active
man-in-the-middle is actually masquerading as the target vehicle).  Only
another wireless connectivity option (e.g., WiMax or Satellite) can be used
to call for help to the OEM Director.

Cheers,

- Ira
Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
#19 is proposed as a first cut at this.  Thoughts / comments / edits?

**Comment by jhdalek55** [comment]
Closed via PR #19
