### ISSUE TITLE
Clarifying definitions of trust

### ISSUE THREAD

**Issue by jhdalek55** [uptane/deployment-considerations#85]
What does "trustworthiness” actually mean in the context of Uptane? We need additions to the text that explain this concept and the various way it is implemented. This includes various methods (PKI and non-PKI) of creating hardware "trust anchors," and methods of creating "chains of trust" for resources--with pointers towards relevant Standards.

**Comment by plapczyn** [comment]
Is this related to #83?

**Comment by jhdalek55** [comment]
I would be willing to provide some text to address this issue, but I would need two things: First, recommendations as to where I could find sources for these definitions and second, some idea of where this should go (Standard or Deployment? A literal definition to be added to the glossary, or a paragraph or two somewhere in Deployment Best Practices?    @iramcdonald, perhaps if you could provide some answers to the above, I would be willing to take a first pass at this.

**Comment by iramcdonald** [comment]
Hi Lois,

I'd suggest only Glossary definitions for now (more discussion later in
Deployment Best Practices).

I finally found a working link for the ISO Online Glossary:

https://www.iso.org/obp

Which yields the following for several relevant terms:

** Trustworthy
"stored electronically in an accurate, reliable and usable/readable manner,
ensuring integrity over tim"
- from ISO TR 15801:2009 Document management — Information stored
electronically — Recommendations for trustworthiness and reliability

** Root of Trust
"component that needs to always behave in the expected manner because its
misbehavior cannot be detected
Note: The complete set of Roots of Trust has at least the minimum set of
functions to enable a description of the
platform characteristics that affect the trustworthiness of the platform."
- from ISO/IEC 11889-1:2015 Information technology — Trusted platform
module library — Part 1: Architecture
(which is the ISO standard for TCG TPM 2.0 (first edition))

Also here's the online NIST Glossary:

https://csrc.nist.gov/glossary

which yields the following:

** Trust
"A characteristic of an entity that indicates its ability to perform
certain functions or services correctly, fairly and
impartially, along with assurance that the entity and its identifier are
genuine."
- from US NIST SP800-152 Profile for U.S. Federal Cryptographic Key
Management Systems

** Trustworthiness
"The attribute of a person or enterprise that provides confidence to others
of the qualifications, capabilities, and
reliability of that entity to perform specific tasks and fulfill assigned
responsibilities."
- from US NIST SP800-53rev5 Security and Privacy Controls for Information
Systems and Organizations

Where they overlap, I would add *both* the ISO and US NIST definitions to
the Deployment Best Practices
Glossary.

Cheers,
- Ira


*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
Thanks, Ira. That seems like a simple enough fix. I'll see if I can do this before Tuesday's meeting.

**Comment by jhdalek55** [comment]
I'm going to add the text supplied by Ira and that should close out this issue.

**Comment by jhdalek55** [comment]
Will be resolved once PR #103 is approved and merged

**Comment by jhdalek55** [comment]
Closed via PR #103
