### ISSUE TITLE
Proposal to version control deployment considerations and clarify changelog format

### ISSUE THREAD

**Issue by plapczyn** [uptane/deployment-considerations#89]
For traceability and clear change management, I proposed versioning the deployment considerations document and improving the changelog to using a defined format.

Propose semantic versioning for document version:
https://semver.org/

Propose Changelog format version 1.1.0 for change log:
https://keepachangelog.com/en/1.1.0/

**Comment by jhdalek55** [comment]
I would be happy to reorganize the Changelog to meet the format version suggested here. I understand what semver is, but I'm not quite sure what we have to change. @mnm678 could you address that portion?

**Comment by mnm678** [comment]
The Best Practices for 1.1.0 are going to be released on the website (see uptane/uptane.github.io#35), although I don't know if that covers the Changelog format.

**Comment by jhdalek55** [comment]
I have not had a chance to change the format yet. I can do that tomorrow if you want to hold off.

**Comment by jhdalek55** [comment]
I will change the Changelog tomorrow. I am working on some other Uptane stuff today and I don't think I will get a chance to reformat it.

**Comment by jhdalek55** [comment]
@plapczyn @mnm678 ..apologies for the delay in revising the changelog format. There have been a number of follow-up projects for Uptane that have kept me from this. When I  did sit down today to review the link @plapczyn  provided, it appears, it might it will be a bit more time consuming than I initailly thought...not difficult, just more involved. I am going to do some work on this today and hopefully I can finish it, but we will still need to get it reviewed. I hate, though, to have the release of the Deployment document held up till I can get this finished. Might it be possible to commit the existing html/PDF versions Marina has prepared now and then just update the changelog file when it is ready? If most people feel this is not a good idea, that's fine. I'm just concerned because we have sent out a press release saying the new Deployment Best Practices is available, but it really is not.

**Comment by jhdalek55** [comment]
@plapczyn what else is needed to address this issue?

**Comment by jhdalek55** [comment]
Based on our conversation in today's (2/2) Uptane Standard Meeting, I am closing this issue as we have changed the formatting of the changelog and did follow semantic versioning numbering.
